### ISSUE TITLE
Publish latest to NPM

### ISSUE THREAD

**Issue by swashcap** [node-browser-compat/dom-storage#6]
My team is readying software for distribution, and we need to make sure all dependencies have licenses. I’m using [license-checker](https://github.com/davglass/license-checker) to ensure every package has a license. It’s unfortunately complaining about dom-storage. I see that you added a license (#2) but this isn’t apparent as NPM’s latest version doesn’t include the license:

![dom-storage-license](https://cloud.githubusercontent.com/assets/1858316/12341753/c646c24c-bad8-11e5-95ef-d8e6e7c7c46f.jpg)

Could you please bump to 2.0.2 and publishing?

**Comment by swashcap** [comment]
Hi, just checking back in. Any updates, @coolaj86?

**Comment by coolaj86** [comment]
Hey, will do.

**Comment by swashcap** [comment]
Awesome, thank you!

**Comment by coolaj86** [comment]
Done. I just blindly published assuming that my last update was license only. Let me know if there are any problems.

... and the diff log confirms it.

**Comment by coolaj86** [comment]
Merged new PRs and published as dom-storage@2.1.0

https://git.coolaj86.com/coolaj86/dom-storage.js
